version: "2.1"
services:
  heimdall:
    image: ghcr.io/linuxserver/heimdall
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    networks:
      - lsio
    volumes:
      - /srv/priv/services/heimdall:/config
    ports:
      - 8080:80
        #      - 4443:443
    restart: unless-stopped

networks:
  lsio:
    driver: bridge
    external: true
