---
version: "2.1"
services:
  airsonic:
    image: lscr.io/linuxserver/airsonic-advanced
    container_name: airsonic-advanced
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - CONTEXT_PATH=<F2>airsonic #optional
#      - JAVA_OPTS=<options> #optional
    volumes:
      - airsonic_config:/config
      - /srv/pub/music:/music
      - /srv/pub/playlists:/playlists
#      - </path/to/podcasts>:/podcasts
#      - </path/to/other media>:/media #optional
    ports:
      - 4040:4040
    devices:
#      - /dev/snd:/dev/snd #optional
    restart: unless-stopped

  networks:
    lsio:
      driver: bridge
      external: true
