version: "2.1"
services:
  airsonic:
    image: ghcr.io/linuxserver/airsonic
    container_name: airsonic
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - CONTEXT_PATH=/airsonic
#      - JAVA_OPTS=<options> #optional
    networks:
      - lsio
    volumes:
      - /srv/priv/services/airsonic/config:/config
      - /srv/pub/music:/music
      - /srv/priv/services/airsonic/playlists:/playlists
      - /srv/priv/services/airsonic/podcasts:/podcasts
#      - </path/to/other media>:/media #optional
    ports:
      - 4040:4040
    devices:
      - /dev/snd:/dev/snd #optional
    restart: unless-stopped

networks:
  lsio:
    driver: bridge
    external: true
